# Generated by Django 5.2.17 on 2026-09-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_flags',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
