# Generated by Django 5.2.17 on 2026-09-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_moderators_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPendingReview',
            fields=[
            ],
            options={
                'verbose_name': 'Post pending review',
                'verbose_name_plural': 'Posts pending review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.post',),
        ),
    ]
